Add support for group and project audit events API
xanzy/go-gitlab pull request #1042
Opened 2021-01-21 19:52 UTC by cmmarslender

https://github.com/xanzy/go-gitlab/issues/1041

2021-01-24 14:42 UTC, svanharmelen requested changes
Thanks @cmmarslender! Have a few suggestions/tweaks, but looks good. Also it seems the instance audit events are omitted. Maybe we should add those as well to make the new service complete? But I can do that as well, so feel free to only fix the current PR!

2021-01-24 14:42 UTC, svanharmelen commented on audit_events.go
> +	TargetID      TargetID    `json:"target_id"` // Sometimes this is an int and sometimes is a string with project path
I prefer to use this field as an `interface{}` is this case. That seems to be more inline with the other locations were an ID that can be both a string and an integer.

2021-01-24 14:42 UTC, svanharmelen commented on audit_events.go
> +func (s *AuditEventsService) GetProjectAuditEvent(pid interface{}, aid interface{}, options ...RequestOptionFunc) (*AuditEvent, *Response, error) {
```suggestion
func (s *AuditEventsService) GetProjectAuditEvent(pid interface{}, event int, options ...RequestOptionFunc) (*AuditEvent, *Response, error) {
```

2021-01-24 14:42 UTC, svanharmelen commented on audit_events.go
> +
```suggestion
```

2021-01-24 14:42 UTC, svanharmelen commented on audit_events.go
> +	u := fmt.Sprintf("projects/%s/audit_events/%s", pathEscape(project), pathEscape(auditEventID))
```suggestion
	u := fmt.Sprintf("projects/%s/audit_events/%d", pathEscape(project), event)
```

2021-01-24 14:42 UTC, svanharmelen commented on audit_events.go
> +	a := new(AuditEvent)
```suggestion
	ae := new(AuditEvent)
```

2021-01-24 14:42 UTC, svanharmelen commented on audit_events.go
> +func (s *AuditEventsService) GetGroupAuditEvent(gid interface{}, aid interface{}, options ...RequestOptionFunc) (*AuditEvent, *Response, error) {
Same changes that I suggested to `GetProjectAuditEvent` apply here...

2021-01-25 18:53 UTC, cmmarslender commented
@svanharmelen Applied the suggestions. I didn't do the instance audit events since I was testing this against gitlab.com and don't have admin there.. I might be able to tackle that against my self hosted instance in a later PR if you don't beat me to it :)

2021-01-26 08:18 UTC, svanharmelen approved these changes
Tweaked stuff a little, but looks now! Thanks @cmmarslender!

2021-01-26 10:38 UTC, merged