Added support for group share with group api
xanzy/go-gitlab pull request #1060
Opened 2021-02-08 13:23 UTC by markuslackner

This PR adds support to share a group with another group.  Its the equivalent of `Projects.ShareProjectWithGroup` and `Projects.DeleteSharedProjectFromGroup` for groups.

API: https://docs.gitlab.com/ee/api/groups.html#create-a-link-to-share-a-group-with-another-group

2021-02-08 13:56 UTC, markuslackner commented
Not sure why the build fails:

```
The command "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.35.0/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.35.0" failed and exited with 56 during .
```

2021-02-11 08:10 UTC, svanharmelen requested changes
Thanks @markuslackner! I do have a couple of suggestions, but nothing major...

2021-02-11 08:10 UTC, svanharmelen commented on groups.go
> +// DeleteSharedGroupFromGroup allows to unshare a group from a group.
```suggestion
// UnshareGroupFromGroup unshares a group from another group.
```

2021-02-11 08:10 UTC, svanharmelen commented on groups.go
> +// ShareGroupWithGroup allows to share a group with a group.
```suggestion
// ShareGroupWithGroup shares a group with another group.
```

2021-02-11 08:10 UTC, svanharmelen commented on groups.go
> +// GitLab API docs: https://docs.gitlab.com/ee/api/groups.html#delete-link-sharing-group-with-another-group
```suggestion
// GitLab API docs:
// https://docs.gitlab.com/ee/api/groups.html#delete-link-sharing-group-with-another-group
```

2021-02-11 08:10 UTC, svanharmelen commented on groups.go
> +func (s *GroupsService) DeleteSharedGroupFromGroup(gid interface{}, groupID int, options ...RequestOptionFunc) (*Response, error) {
```suggestion
func (s *GroupsService) UnshareGroupFromGroup(gid interface{}, groupID int, options ...RequestOptionFunc) (*Response, error) {
```

2021-02-11 13:54 UTC, markuslackner commented
I have added your suggestions. Btw thanks a lot for your great work!

2021-02-11 14:42 UTC, svanharmelen approved these changes
Thanks @markuslackner! LGTM!

2021-02-11 14:42 UTC, merged