Add GetUser with_custom_attributes option
xanzy/go-gitlab pull request #1124
Opened 2021-04-05 19:14 UTC by ax1036

Add missing `with_custom_attributes` option for `GetUser` (need admin account)

Gitlab docs:

![image](https://user-images.githubusercontent.com/30216166/113615068-ac2cc800-9653-11eb-8520-6a69958bbb18.png)

2021-04-06 06:39 UTC, svanharmelen requested changes

2021-04-06 06:39 UTC, svanharmelen commented on users.go
> +	// The options below are only available for admins.
```suggestion
```

2021-04-12 06:39 UTC, svanharmelen approved these changes
Thanks @ax1036. While this is a breaking change, I'm afraid we have to change this to keep the package inline with the API. So LGTM 👍🏻

2021-04-12 06:39 UTC, merged

2021-04-12 07:24 UTC, ax1036 commented
> Thanks @ax1036. While this is a breaking change, I'm afraid we have to change this to keep the package inline with the API. So LGTM 👍🏻

Yes, I hope this will not broke too many people code :ok_hand: