Add DirectAssetURL, FilePath & LinkType to Release Links API
xanzy/go-gitlab pull request #1135
Opened 2021-04-20 16:13 UTC by 56KBs

Add optional DirectAssetURL and LinkType for Release Links response data.

Add optional FilePath and LinkType to creation and updating of release links.

See https://docs.gitlab.com/13.10/ee/api/releases/links.html#create-a-link for documentation

2021-04-26 08:50 UTC, svanharmelen requested changes
Thanks @56KBs! Do have some comments, mostly making the ordering consistent with the docs and one functional suggestion...

2021-04-26 08:50 UTC, svanharmelen commented on releaselinks.go
> +	LinkType       string `json:"link_type,omitempty"`
```suggestion
	DirectAssetURL string `json:"direct_asset_url"`
	External       bool   `json:"external"`
	LinkType       string `json:"link_type"`
```

2021-04-26 08:50 UTC, svanharmelen commented on fixtures_test.go
> +		"link_type": "other"
```suggestion
		"direct_asset_url": "http://192.168.10.15:3000/namespace/example/-/releases/v0.1/downloads/awesome-v0.2.dmg",
		"external":true,
		"link_type": "other"
```

2021-04-26 08:50 UTC, svanharmelen commented on fixtures_test.go
> +			"external": false
```suggestion
			"direct_asset_url": "http://192.168.10.15:3000/namespace/example/-/releases/v0.1/downloads/awesome-v0.2.dmg",
			"external": false,
			"link_type": "other"
```

2021-04-26 08:50 UTC, svanharmelen commented on releaselinks.go
> +	URL      *string `url:"url" json:"url"`
Not your change, but let's fix it while were add it 😉 
```suggestion
	Name     *string `url:"name,omitempty" json:"name,omitempty"`
	URL      *string `url:"url,omitempty" json:"url,omitempty"`
```

2021-04-26 08:50 UTC, svanharmelen commented on releaselinks_test.go
> +		DirectAssetURL: "http://192.168.10.15:3000/namespace/example/-/releases/v0.1/downloads/awesome-v0.2.dmg",
```suggestion
		DirectAssetURL: "http://192.168.10.15:3000/namespace/example/-/releases/v0.1/downloads/awesome-v0.2.dmg",
		External:       true,
```

2021-04-26 08:50 UTC, svanharmelen commented on releaselinks_test.go
> +				External:       false,
```suggestion
				External:       false,
				LinkType:       "other",
```

2021-04-26 08:50 UTC, svanharmelen commented on releaselinks_test.go
> +			DirectAssetURL: "http://192.168.10.15:3000/namespace/example/-/releases/v0.1/downloads/awesome-v0.2.dmg",
```suggestion
			DirectAssetURL: "http://192.168.10.15:3000/namespace/example/-/releases/v0.1/downloads/awesome-v0.2.dmg",
			External:       false,
```

2021-04-26 08:50 UTC, svanharmelen commented on releaselinks.go
> +	LinkType       string `json:"link_type,omitempty"`
I think this needs a `const`, like this for example: https://github.com/xanzy/go-gitlab/blob/master/types.go#L36

2021-04-27 08:49 UTC, 56KBs commented
> Thanks @56KBs! Do have some comments, mostly making the ordering consistent with the docs and one functional suggestion...

Thanks @svanharmelen - I've fixed up the ordering and the other comments :+1:

2021-05-10 08:14 UTC, svanharmelen approved these changes
Thanks @56KBs! LGTM 👍🏻

2021-05-10 08:15 UTC, merged

2021-05-13 09:45 UTC, 56KBs commented
@svanharmelen would it be possible to get a release that contains these changes, I would like to make use of these changes within [goreleaser/goreleaser](https://github.com/goreleaser/goreleaser)

2021-05-13 10:01 UTC, svanharmelen commented
Just release v0.50.0 👍🏻