ListJobsOptions: support include_retried parameter
xanzy/go-gitlab pull request #1143
Opened 2021-05-06 12:07 UTC by JordanP

The `include_retried` parameter of the List pipeline jobs API call was introduced in Gitlab 13.9: https://docs.gitlab.com/ee/api/jobs.html#list-pipeline-jobs

2021-05-09 07:32 UTC, svanharmelen requested changes
Thanks @JordanP, just a small request to keep things consistent...

2021-05-09 07:32 UTC, svanharmelen commented on jobs.go
> +	IncludeRetried bool              `url:"include_retried,omitempty" json:"include_retried,omitempty"`
Please use the ordering from the docs, meaning this should be below `Scope`

2021-05-10 08:21 UTC, svanharmelen approved these changes
I've switched them for you, looks fine now. Thanks @JordanP 👍🏻

2021-05-10 08:21 UTC, merged

2021-05-10 08:26 UTC, JordanP commented
@svanharmelen thanks ! I was about to do it this morning, you beat me to it. Thanks for the quick merge !