Assignees
xanzy/go-gitlab pull request #1152
Opened 2021-05-25 18:35 UTC by maxice8

The data used to find those out is from `gitlab.alpinelinux.org` (GitLab Community Edition 13.9.7)

```json
  "assignees": [
    {
      "id": 1589,
      "name": "Leo",
      "username": "Leo",
      "avatar_url": "https://gitlab.alpinelinux.org/uploads/-/system/user/avatar/1589/avatar.png",
      "email": "meme"
   }
  ]
```

2021-05-25 18:44 UTC, maxice8 commented
Seems like `User1` appears enough the linter wants it `const`

2021-05-25 19:41 UTC, svanharmelen requested changes
One small comment, and guess you need to fix the linter comment as well 😞

2021-05-25 19:41 UTC, svanharmelen commented on event_webhook_types.go
> +	Assignees  []MergeAssignee `json:"assignees"`
```suggestion
	Assignees  []*MergeAssignee `json:"assignees"`
```

2021-05-25 19:47 UTC, svanharmelen commented
If you rebase the linter should not complain anymore 🤞🏻

2021-05-26 03:09 UTC, maxice8 commented on event_webhook_types.go
> +	Assignees  []MergeAssignee `json:"assignees"`
Thanks, applied

2021-05-26 06:44 UTC, maxice8 commented
Made them constants.

2021-05-26 20:01 UTC, svanharmelen approved these changes
Thanks @maxice8 👍🏻

2021-05-26 20:02 UTC, merged