Avatar support
xanzy/go-gitlab pull request #1155
Opened 2021-05-26 20:14 UTC by pkostohrys

2021-05-30 14:39 UTC, svanharmelen requested changes
Thanks @pkostohrys, but it needs some work before we can merge it. Please checkout the rest of the codebase and try to make sure your PR is consistent with it 👍🏻

2021-05-30 14:39 UTC, svanharmelen commented on avatar.go
> +	}{}
I prefer to create and return a struct instead:

```
type Avatar struct {
    AvatarURL string `json:"avatar_url"`
}
```

2021-05-30 14:39 UTC, svanharmelen commented on avatar.go
> +}
These should be pointers, the struct should be places above the `GetAvatar` method and this the struct should be called `GetAvatarOptions`...

2021-05-30 14:39 UTC, svanharmelen commented on avatar.go
> +	return nil, &avatar.Url
We always return the response as well.

2021-05-30 21:29 UTC, pkostohrys commented
Thank @svanharmelen for you comments. I have pushed an update. Could you please check it now ?

2021-05-31 07:58 UTC, svanharmelen approved these changes
Thanks @pkostohrys! I've updated the code a little to fix the last inconsistencies. Please check the latest commit to see what I've changed 👍🏻

2021-05-31 07:58 UTC, merged