feature: Added Plan Limits
xanzy/go-gitlab pull request #1214
Opened 2021-09-11 09:49 UTC by Urento

Docs: https://docs.gitlab.com/ee/api/plan_limits.html

2021-09-17 08:23 UTC, svanharmelen requested changes

2021-09-17 08:23 UTC, svanharmelen commented on plan_limits.go
> +	TerraformModuleMaxFileSize *int    `json:"terraform_module_max_file_size,omitempty"`
These should all not be pointers and should be ordered alphabetically following the docs.

2021-09-17 08:23 UTC, svanharmelen commented on plan_limits.go
> +func (s *PlanLimitsService) GetCurrentPlanLimits(options ...RequestOptionFunc) (*PlanLimit, *Response, error) {
This one needs an options struct that takes a `PlanName`

2021-09-17 08:23 UTC, svanharmelen commented on plan_limits.go
> +}
Option structs are made individually for a method. Please see the other code in this repo and follow the same pattern.

2021-09-17 08:23 UTC, svanharmelen commented on plan_limits.go
> +// Modify the limits of a plan on the GitLab instance.
This will give a linter warning

2021-09-17 08:23 UTC, svanharmelen commented on plan_limits.go
> +// List the current limits of a plan on the GitLab instance.
This will give a linter warning.

2021-09-23 18:05 UTC, Urento commented
I will fix these next week

2021-10-19 14:52 UTC, merged