feat: add markdown endpoint support
xanzy/go-gitlab pull request #1303
Opened 2021-12-02 16:19 UTC by doriandekoning

I noticed that the markdown (https://docs.gitlab.com/ee/api/markdown.html) endpoint is not implemented. So I've added it, I wasn't really sure on the naming of the functions since it's not a get route and technically it retrieves HTML. However, I decided to follow the name in the url/docs of gitlab with just `Markdown`. If you like an other name please let me know, I'd be happy to change it :)

2021-12-03 12:41 UTC, svanharmelen requested changes

2021-12-03 12:41 UTC, svanharmelen commented on markdown.go
> +type MarkdownRequestsService struct {
Following the docs, I think this should be called `MarkdownService` instead.

2021-12-03 12:41 UTC, svanharmelen commented on markdown.go
> +type MarkdownResponse struct {
```suggestion
type Markdown struct {
```

2021-12-03 13:03 UTC, doriandekoning commented
@svanharmelen  Thanks for the review, I've changed it according to the suggestions.

2021-12-03 14:43 UTC, svanharmelen requested changes

2021-12-03 14:43 UTC, svanharmelen commented on markdown.go
> +// MarkdownService handles communication with the markdown endpoint of the gitlab API
```suggestion
// MarkdownService handles communication with the markdown related methods of the GitLab API.
```

2021-12-03 14:43 UTC, svanharmelen commented on markdown.go
> +// Markdown represents gitlab markdown
```suggestion
// Markdown represents a markdown document.
//
// Gitlab API docs: https://docs.gitlab.com/ee/api/markdown.html
```

2021-12-03 14:43 UTC, svanharmelen commented on markdown.go
> +// MarkdownOptions represents the available Markdown() options.
```suggestion
// RenderOptions represents the available Render() options.
//
// Gitlab API docs:
// https://docs.gitlab.com/ee/api/markdown.html#render-an-arbitrary-markdown-document
```

2021-12-03 14:43 UTC, svanharmelen commented on markdown.go
> +// Gitlab API docs:
```suggestion
// Render an arbitrary markdown document.
//
// Gitlab API docs:
// https://docs.gitlab.com/ee/api/markdown.html#render-an-arbitrary-markdown-document
```

2021-12-03 14:43 UTC, svanharmelen commented on markdown.go
> +func (s *MarkdownService) Markdown(opt *MarkdownOptions, options ...RequestOptionFunc) (*Markdown, *Response, error) {
```suggestion
func (s *MarkdownService) Render(opt *RenderOptions, options ...RequestOptionFunc) (*Markdown, *Response, error) {
```

2021-12-03 14:43 UTC, svanharmelen commented on markdown.go
> +	return markdown, response, nil
```suggestion
	}
	
	return md, response, nil
```

2021-12-03 14:43 UTC, svanharmelen commented on markdown.go
> +	response, err := s.client.Do(req, markdown)
```suggestion
	md := new(Markdown)
	response, err := s.client.Do(req, md)
```

2021-12-03 14:43 UTC, svanharmelen commented on markdown.go
> +	Project                 string `json:"project,omitempty"`
These all need to be pointers and they are missing the `url` tags.

2021-12-03 14:43 UTC, svanharmelen commented on markdown.go
> +type MarkdownOptions struct {
```suggestion
type RenderOptions struct {
```

2021-12-05 08:36 UTC, svanharmelen approved these changes
I rebased and tweaked the PR a little to incorporate the requested changes.

2021-12-05 08:40 UTC, merged