Update ListSSHKeysForUser to match API definition allowing id or user…
xanzy/go-gitlab pull request #1369
Opened 2022-02-08 19:40 UTC by pschwartz

…name

Signed-off-by: Philip Marc Schwartz <Philip.Schwartz1@T-Mobile.com>

2022-02-08 19:40 UTC, pschwartz commented
@svanharmelen Another fix correcting an API call to match the API doc.

2022-02-09 15:27 UTC, svanharmelen requested changes
Two very minor suggestions, looks fine otherwise!

2022-02-09 15:27 UTC, svanharmelen commented on users.go
> +// ListSSHKeysForUser gets a list of a specified user's SSH keys. A
```suggestion
// ListSSHKeysForUser gets a list of a specified user's SSH keys.
```

2022-02-09 15:27 UTC, svanharmelen commented on users.go
> +	u := fmt.Sprintf("users/%s/keys", user)
```suggestion
	}
	u := fmt.Sprintf("users/%s/keys", user)
```

2022-02-09 15:35 UTC, svanharmelen approved these changes
Thanks! LGTM 👍🏻

2022-02-09 15:35 UTC, merged