Support endpoint to get and delete project mirror
xanzy/go-gitlab pull request #1432
Opened 2022-03-26 16:35 UTC by timofurrer

I have recently introduced this in GitLab 14.10:

* https://docs.gitlab.com/ee/api/remote_mirrors.html#get-a-single-projects-remote-mirror
* https://docs.gitlab.com/ee/api/remote_mirrors.html#delete-a-remote-mirror

2022-03-29 09:28 UTC, jtymes requested changes

2022-03-29 09:28 UTC, jtymes commented on project_mirror.go
> +// GetProjectMirror gets a single mirrors configured on the project.
```suggestion
// GetProjectMirror gets a single mirror configured on the project.
```

2022-03-29 09:46 UTC, jtymes approved these changes

2022-04-02 15:57 UTC, svanharmelen approved these changes
Nice one, thanks 👍🏻

2022-04-02 15:57 UTC, merged