Add support to protect tags with group_id or user_id
xanzy/go-gitlab pull request #1540
Opened 2022-09-01 00:54 UTC by weirdian2k3

This resolves https://github.com/xanzy/go-gitlab/issues/1511

2022-10-27 03:45 UTC, weirdian2k3 commented
@svanharmelen would you be able to review this? I'm hoping get this updated so that I can get a downstream issue resolved

2022-10-27 08:47 UTC, svanharmelen requested changes

2022-10-27 08:47 UTC, svanharmelen commented on protected_tags.go
> +	GroupID                *int             `url:"group_id,omitempty" json:"group_id,omitempty"`
I cannot see in the docs that these fields need to be here. Can you point me to somewhere (in the code) that shows these fields exist in this struct?

Additionally in a response struct like this we don't use pointers for build-in types and URL tags.

2022-10-27 08:47 UTC, svanharmelen commented on protected_tags.go
> +type ProtectRepositoryTagsPermissionOptions struct {
Maybe make this just a little shorter, like `TagsPermissionOptions` or something?

2022-10-27 08:47 UTC, svanharmelen commented on protected_tags.go
> +	AllowedToCreate   *[]ProtectRepositoryTagsPermissionOptions `url:"allowed_to_create,omitempty" json:"allowed_to_create,omitempty"`
```suggestion
	AllowedToCreate   *[]*ProtectRepositoryTagsPermissionOptions `url:"allowed_to_create,omitempty" json:"allowed_to_create,omitempty"`
```

2022-10-29 12:50 UTC, svanharmelen approved these changes
I'm still not sure if these (`user_id` and `group_id`) fields exist in the `TagAccessDescription` response, but I fixed up the PR and went ahead to merge it...

2022-10-29 12:51 UTC, merged