feat: add support for getting DORA metrics from projects and groups
xanzy/go-gitlab pull request #1582
Opened 2022-11-26 21:00 UTC by 2785

resolves https://github.com/xanzy/go-gitlab/issues/1557

2022-12-01 13:25 UTC, jimmy0012 requested changes
Was testing this and ran into an issue. Sometimes Dora metrics are not integers so these functions will not be able to marshal the json:
`   error="error fetching DORA Metric leadTime for <repo>: json: cannot unmarshal number 607.5 into Go struct field DORAMetric.value of type int" project-name=<repo>`

2022-12-01 21:36 UTC, 2785 commented
:neutral_face:  I so wish there's a day that gitlab docs actually tell you that

2022-12-03 13:01 UTC, svanharmelen requested changes

2022-12-03 13:01 UTC, svanharmelen commented on dora_metrics.go
> +
```suggestion
```

While I understand this, I prefer to let the API return this info instead.

2022-12-03 13:01 UTC, svanharmelen commented on dora_metrics.go
> +// GitLab API Docs: https://docs.gitlab.com/ee/api/dora/metrics.html#get-group-level-dora-metrics
```suggestion
// GitLab API Docs:
// https://docs.gitlab.com/ee/api/dora/metrics.html#get-group-level-dora-metrics
```

2022-12-03 13:01 UTC, svanharmelen commented on dora_metrics.go
> +
```suggestion
```

2024-09-08 15:04 UTC, heidiberry commented
This PR can be closed without merging, the functionality was added under https://github.com/xanzy/go-gitlab/pull/1931

2024-09-08 15:15 UTC, svanharmelen commented
Thanks for the ping @heidiberry 👍🏻

2024-09-08 15:15 UTC, closed without merging