Add 'start housekeeping task for a project' feature
xanzy/go-gitlab pull request #1585
Opened 2022-11-29 15:36 UTC by cyd01

Add **Start the Housekeeping task for a project** feature.

Reference:  
https://docs.gitlab.com/ee/api/projects.html#start-the-housekeeping-task-for-a-project

2022-12-03 12:44 UTC, svanharmelen requested changes
Two comments, rest looks good 👍🏻

2022-12-03 12:44 UTC, svanharmelen commented on projects.go
> +	return resp, err
```suggestion
	return s.client.Do(req, nil)
```

2022-12-03 12:44 UTC, svanharmelen commented on projects.go
> +	CreatedAt         string `json:"created_at"`
```suggestion
	CreatedAt         *time.Time `json:"created_at"`
```

2022-12-05 11:16 UTC, cyd01 commented on projects.go
> +	return resp, err
You are right. It's very much better.

2022-12-10 12:44 UTC, svanharmelen approved these changes
Thanks for the fixes 👍🏻  LGTM now...

2022-12-10 12:45 UTC, merged