update gitlab project event struct
xanzy/go-gitlab pull request #1673
Opened 2023-03-15 11:32 UTC by chenggui53

It seems gitlab project event api has upgrade, and the old struct is not correct to now api, so i update the project event struct to match the new api.

2023-03-15 11:52 UTC, svanharmelen requested changes

2023-03-15 11:52 UTC, svanharmelen commented on oryxBuildBinary
Please remove this file from the PR

2023-03-15 11:52 UTC, svanharmelen commented on projects.go
> -	} `json:"data"`
This is still a valid field.

2023-03-15 11:52 UTC, svanharmelen commented on projects.go
> +	PushData       interface{} `json:"push_data"`
I don't see a field called `push_data` in the docs...

2023-03-15 11:52 UTC, svanharmelen commented on projects.go
> +	Note           interface{} `json:"note"`
This needs to be a typed struct. The IDs are `interface{}`'es because they can be either a string or int, but the rest should all be typed.

2023-03-15 11:52 UTC, svanharmelen commented on projects.go
> +}
I thing this matches the `EventUser`?

2023-03-20 13:01 UTC, svanharmelen commented
@chenggui53 can you have a look and check if this is actually what you want?

2023-03-30 11:08 UTC, chenggui53 commented
> @chenggui53 can you have a look and check if this is actually what you want?

@svanharmelen yes, and i have add push data field and its test from gitlab doc.

2023-03-31 09:03 UTC, svanharmelen approved these changes
Thanks @chenggui53 👍🏻

2023-03-31 09:08 UTC, merged