Implement raw field for instance variables API
xanzy/go-gitlab pull request #1682
Opened 2023-04-04 12:56 UTC by timofurrer

2023-04-04 12:57 UTC, timofurrer commented
@svanharmelen do you mind giving this a review and release? 🙏

2023-04-05 06:44 UTC, svanharmelen requested changes

2023-04-05 06:44 UTC, svanharmelen commented on instance_variables.go
> +	Raw          bool               `url:"raw,omitempty" json:"raw,omitempty"`
This needs to be a pointer...

2023-04-05 06:44 UTC, svanharmelen commented on instance_variables.go
> +	Raw          bool               `url:"raw,omitempty" json:"raw,omitempty"`
This needs to be a pointer...

2023-04-05 09:05 UTC, svanharmelen approved these changes
Thanks, LGTM!

2023-04-05 09:06 UTC, merged