Replaced Visibility with VisibilityLevel in Webhooks
xanzy/go-gitlab pull request #1701
Opened 2023-04-14 15:29 UTC by smit-modi

GitLab doesn't return Visibility with string type anymore. It returns VisibilityLevel with int type.

2023-04-25 19:50 UTC, smit-modi commented
@svanharmelen Can you please review this?

2023-04-27 14:37 UTC, svanharmelen requested changes
Besides the one minor comment, I'm a little bit unsure what this change means for backwards compatibility. Can you tell from what version GitLab changed this behavior?

I guess the easiest way to keep supporting older versions is to not change the existing field, but instead add the new field next to the existing one...

Or do you have any other thoughts?

2023-04-27 14:37 UTC, svanharmelen commented on types.go
> +
```go
// VisibilityLevel is a helper routine that allocates a new
// VisibilityLevelValue to store v and returns a pointer to it.
func VisibilityLevel(v VisibilityLevelValue) *VisibilityLevelValue {
	p := new(VisibilityLevelValue)
	*p = v
	return p
}
```

Can you add something like this ☝🏻 I try to add such a helper function for all custom types to make it easier for people to get a pointer to such a value (which is needed in option structs).

2024-12-10 15:50 UTC, timofurrer commented
@smit-modi we've migrated the repository over to [GitLab.com](https://gitlab.com/gitlab-org/api/client-go).

Please see https://github.com/xanzy/go-gitlab/issues/2060#issuecomment-2532116371 for more context.

2024-12-10 15:50 UTC, closed without merging