Add support for model_experiments_access_level at projects
xanzy/go-gitlab pull request #1856
Opened 2023-12-15 15:51 UTC by christianschmizz

2023-12-16 12:21 UTC, svanharmelen requested changes

2023-12-16 12:21 UTC, svanharmelen commented on oryxBuildBinary
Please remove this fine from the PR 😏

2023-12-18 11:23 UTC, christianschmizz commented on oryxBuildBinary
Thank you for your attention!

2023-12-18 14:20 UTC, svanharmelen approved these changes
LGTM! Thanks @christianschmizz 👍🏻

2023-12-18 14:27 UTC, merged