Add support for setting token expiration
xanzy/go-gitlab pull request #1907
Opened 2024-04-02 13:52 UTC by dieterdemeyer

When creating a Personal Access Token for a Service Account, it's possible to also pass an expiry date (optional).
This PR adds support for this.

2024-04-03 11:39 UTC, dieterdemeyer commented
@svanharmelen - This PR is ready for your review.

It's not my intention to be pushy but I was wondering when we could see this get merged and released.
The reason for asking is because I'm currently blocked on having this feature, hence my PR to get this added 😉 
If you have any feedback on the code that needs looking at, please let me know.

2024-04-03 14:17 UTC, svanharmelen requested changes

2024-04-03 14:17 UTC, svanharmelen commented on group_serviceaccounts.go
> +	ExpiresAt *string   `url:"expires_at,omitempty" json:"expires_at,omitempty"`
```suggestion
	ExpiresAt *ISOTime   `url:"expires_at,omitempty" json:"expires_at,omitempty"`
```

I guess this should be `ISOTime`?

2024-04-03 16:37 UTC, dieterdemeyer commented on group_serviceaccounts.go
> +	ExpiresAt *string   `url:"expires_at,omitempty" json:"expires_at,omitempty"`
Updated 👍

2024-04-05 07:07 UTC, svanharmelen approved these changes
Thanks @dieterdemeyer 👍🏻

2024-04-05 07:08 UTC, merged

2024-04-05 14:07 UTC, dieterdemeyer commented
@svanharmelen Thanks for merging 👍 .  
Any indication on when we can expect a new release that will include this change?

2024-04-05 14:16 UTC, svanharmelen commented
Uuh... Am I missing anything? `v0.102.0` contains these commits right?

2024-04-05 14:45 UTC, dieterdemeyer commented
My bad, I thought it only contained the drafts-support commit (when looking at the tags view) 🙃 
Forget I said anything!