Resolves #1405: only one endpoint was missing
xanzy/go-gitlab pull request #1927
Opened 2024-05-03 15:12 UTC by heidiberry

Comparing the endpoints to the documentation here: https://docs.gitlab.com/ee/api/status_checks.html there is only one endpoint not currently supported. This is https://docs.gitlab.com/ee/api/status_checks.html#retry-failed-status-check-for-a-merge-request

I've added a new function for this endpoint and a very basic test.

2024-05-03 15:13 UTC, heidiberry commented
https://github.com/xanzy/go-gitlab/issues/1405

2024-05-04 12:41 UTC, svanharmelen requested changes

2024-05-04 12:41 UTC, svanharmelen commented on external_status_checks.go
> +func (s *ExternalStatusChecksService) RetryFailedStatusCheckForAMergeRequest(pid interface{}, mergeRequest int, opt *RetryFailedStatusCheckForAMergeRequestOptions, options ...RequestOptionFunc) (*Res
All the params that are part of the URL are passed as function parameters. The option structs are only used for sending options to the API which in this case is not applicable as all params are art of the URL and not request body is expected.

2024-05-05 09:04 UTC, svanharmelen approved these changes
Thanks @heidiberry, LGTM 👍🏻

2024-05-05 09:07 UTC, merged