Add support for custom webhook headers
xanzy/go-gitlab pull request #1951
Opened 2024-06-05 18:12 UTC by PatrickRice-KSC

With 17.1, GitLab now supports the ability to set custom headers on webhooks. 

See the API documentation here: 
Add/Edit: https://docs.gitlab.com/ee/api/projects.html#edit-project-hook
Set Header: https://docs.gitlab.com/ee/api/projects.html#set-a-custom-header
Delete Header: https://docs.gitlab.com/ee/api/projects.html#delete-a-custom-header

Note that the `value` of the header will never come back from the API, you can only ever _set_ it (with these APIs). 

Support for the Group Webhook will come in a subsequent PR

2024-06-05 18:13 UTC, PatrickRice-KSC commented
@svanharmelen - This PR should be ready for review when you have a moment!

2024-06-11 06:51 UTC, svanharmelen requested changes
I acknowledge this feels weird `*[]*HookCustomHeader`, but it allows you to make a difference between an empty slice and no value set at all which in some API is needed. So for consistence sake I want to use this pattern in all option structs.

2024-06-11 06:51 UTC, svanharmelen commented on group_hooks.go
> +	CustomHeaders             []HookCustomHeader `url:"custom_headers,omitempty" json:"custom_headers,omitempty"`
```suggestion
	CustomHeaders             []*HookCustomHeader `url:"custom_headers,omitempty" json:"custom_headers,omitempty"`
```

2024-06-11 06:51 UTC, svanharmelen commented on group_hooks.go
> +	CustomHeaders             []*HookCustomHeader `url:"custom_headers,omitempty" json:"custom_headers,omitempty"`
```suggestion
	CustomHeaders             *[]*HookCustomHeader `url:"custom_headers,omitempty" json:"custom_headers,omitempty"`
```

2024-06-11 06:51 UTC, svanharmelen commented on group_hooks.go
> +	CustomHeaders             []*HookCustomHeader `url:"custom_headers,omitempty" json:"custom_headers,omitempty"`
```suggestion
	CustomHeaders             *[]*HookCustomHeader `url:"custom_headers,omitempty" json:"custom_headers,omitempty"`
```

2024-06-11 06:51 UTC, svanharmelen commented on projects.go
> +	CustomHeaders             []HookCustomHeader `json:"custom_headers"`
```suggestion
	CustomHeaders             []*HookCustomHeader `json:"custom_headers"`
```

2024-06-11 06:51 UTC, svanharmelen commented on projects.go
> +	CustomHeaders             []*HookCustomHeader `url:"custom_headers,omitempty" json:"custom_headers,omitempty"`
```suggestion
	CustomHeaders             *[]*HookCustomHeader `url:"custom_headers,omitempty" json:"custom_headers,omitempty"`
```

2024-06-11 06:51 UTC, svanharmelen commented on projects.go
> +	CustomHeaders             []*HookCustomHeader `url:"custom_headers,omitempty" json:"custom_headers,omitempty"`
```suggestion
	CustomHeaders             *[]*HookCustomHeader `url:"custom_headers,omitempty" json:"custom_headers,omitempty"`
```

2024-06-11 14:54 UTC, PatrickRice-KSC commented
@svanharmelen  - No problem at all, I completely understand! All changes are made 😄

2024-06-11 15:15 UTC, svanharmelen approved these changes
Thanks @PatrickRice-KSC 👍🏻

2024-06-11 15:15 UTC, merged