feat: add inherited group member api
xanzy/go-gitlab pull request #1958
Opened 2024-06-20 06:35 UTC by nanjingfm

Add the inherited group member API in this PR.

https://docs.gitlab.com/ee/api/members.html#get-a-member-of-a-group-or-project-including-inherited-and-invited-members

2024-06-24 07:37 UTC, svanharmelen requested changes
Few minor suggestions, rest looks good 👍🏻

2024-06-24 07:37 UTC, svanharmelen commented on group_members.go
> +// GetInheritedGroupMember get a member of a group or project, including inherited and invited members
```suggestion
// GetInheritedGroupMember get a member of a group or project, including
// inherited and invited members
```

2024-06-24 07:37 UTC, svanharmelen commented on group_members_test.go
>  	"github.com/stretchr/testify/assert"
```suggestion
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
```

2024-06-24 07:37 UTC, svanharmelen commented on group_members_test.go
> +		// This is pulled straight from a `/group/<group_id>/members/all/<user_id>` call, then obfuscated.
```suggestion
```

2024-07-08 07:40 UTC, an0rak-dev commented
Hi 👋🏻 
Thanks for your work ! I'm quite interested with this endpoint ! Do you have any news about this ? 👀

2024-07-12 13:20 UTC, svanharmelen approved these changes
LGTM! Thanks @nanjingfm 👍🏻

2024-07-12 13:21 UTC, merged