Add TriggerTestProjectHook function to ProjectsService
xanzy/go-gitlab pull request #1966
Opened 2024-07-01 09:51 UTC by bearx3f

From GitLab 17.0+ they add "Trigger a test project hook" to test project's hook

2024-07-12 13:35 UTC, svanharmelen requested changes
Looks good, but needs a small update...

2024-07-12 13:35 UTC, svanharmelen commented on projects.go
> +// an administrator can disable the feature flag named web_hook_test_api_endpoint_rate_limit.
```suggestion
// In GitLab 17.0 and later, this endpoint has a special rate limit.
// In GitLab 17.0 the rate was three requests per minute for each project hook.
// In GitLab 17.1 this was changed to five requests per minute for each project 
// and authenticated user.
//
// To disable this limit on self-managed GitLab and GitLab Dedicated, an 
// administrator can disable the feature flag named web_hook_test_api_endpoint_rate_limit.
```

2024-07-12 13:35 UTC, svanharmelen commented on projects.go
> +)
Can you move this to (the correct ordered location) in `types.go`? Thanks!

2024-07-13 08:26 UTC, bearx3f commented
Hi, thanks for your comment, I changed as your suggestion.

2024-07-13 08:46 UTC, svanharmelen approved these changes
Thanks @bearx3f 👍🏻

2024-07-13 08:48 UTC, merged

2024-07-16 03:31 UTC, bearx3f commented
Do you have any updates on its release schedule?

2024-07-16 07:04 UTC, svanharmelen commented
Released `v0.107.0`

2024-07-16 07:52 UTC, bearx3f commented
Thank you very much. I truly appreciate it.