Move PreReceiveSecretDetectionEnabled to Project
xanzy/go-gitlab pull request #1989
Opened 2024-08-18 17:06 UTC by gravis

It was added to the wrong location with !1984

2024-08-18 17:07 UTC, gravis commented
Sorry for that!

2024-08-19 12:11 UTC, svanharmelen requested changes
Guess that is why I normally don't merge PRs with any undocumented fields 😏

2024-08-19 12:11 UTC, svanharmelen commented on projects.go
> +	PreReceiveSecretDetectionEnabled         *bool              `url:"pre_receive_secret_detection_enabled,omitempty" json:"pre_receive_secret_detection_enabled,omitempty"`
```suggestion
	PreReceiveSecretDetectionEnabled         bool              `json:"pre_receive_secret_detection_enabled"`
```

2024-08-19 13:14 UTC, gravis commented
> Guess this is why I normally don't merge PRs with undocumented features 😏

@svanharmelen The documentation for this feature is [here](https://docs.gitlab.com/ee/user/application_security/secret_detection/secret_push_protection/), but I think you are referring to https://docs.gitlab.com/ee/api/projects.html#get-single-project?

2024-08-19 13:29 UTC, svanharmelen approved these changes

2024-08-19 13:30 UTC, svanharmelen commented
Yes indeed... But all is good. Thanks for fixing the issue 👍🏻

2024-08-19 13:30 UTC, merged