Adds support for GitLab project freeze periods API
xanzy/go-gitlab pull request #945
Opened 2020-09-22 16:21 UTC by pcnc

This PR implements the freeze periods API added for projects in GitLab 13.0. 

https://docs.gitlab.com/ee/api/freeze_periods.html

2020-09-22 17:40 UTC, svanharmelen requested changes
Could you make a new service for this called `FreezePeriodsService` and put all the code in a decidated file called `freeze_periods.go`? That would make this new code (API) be inline with how the rest of the package is structured.

Once that I done, I'll review the code itself. But on first glance that looks pretty well...

2020-09-22 17:52 UTC, pcnc commented
Refactored all new code under the `FreezePeriodsService` service, located in a separate service-specific file

2020-09-23 07:30 UTC, svanharmelen reviewed
Only very minor comments which are easy to fix. Rest looks good 👍🏻

2020-09-23 07:30 UTC, svanharmelen commented on freeze_periods.go
> +	var pfp []*FreezePeriod
```suggestion
	var fps []*FreezePeriod
```

2020-09-23 07:30 UTC, svanharmelen commented on freeze_periods.go
> +	pfp := new(FreezePeriod)
```suggestion
	fp := new(FreezePeriod)
```

2020-09-23 07:30 UTC, svanharmelen commented on freeze_periods.go
> +// CreateFreezePeriodOptions represents the available CreateFreezePeriodOptions() options.
```suggestion
// CreateFreezePeriodOptions represents the available CreateFreezePeriodOptions()
// options.
```

2020-09-23 07:30 UTC, svanharmelen commented on freeze_periods.go
> +	CronTimezone *string `json:"cron_timezone,omitempty"`
Please add `url` tags and `omitempty` to all fields here...

2020-09-23 07:30 UTC, svanharmelen commented on freeze_periods.go
> +	pfp := new(FreezePeriod)
```suggestion
	fp := new(FreezePeriod)
```

2020-09-23 07:30 UTC, svanharmelen commented on freeze_periods.go
> +	CronTimezone *string `json:"cron_timezone,omitempty"`
Please add `url` tags...

2020-09-23 07:30 UTC, svanharmelen commented on freeze_periods.go
> +	pfp := new(FreezePeriod)
```suggestion
	fp := new(FreezePeriod)
```

2020-09-23 07:30 UTC, svanharmelen commented on freeze_periods.go
> +}
Please end the file with a newline.

2020-09-23 07:30 UTC, svanharmelen commented on freeze_periods.go
> +// method and can be called multiple times. Either the hook is available or not.
```suggestion
// DeleteFreezePeriod removes a freeze period from a project. This is an
// idempotent method and can be called multiple times. Either the hook is
// available or not.
```

2020-09-23 07:30 UTC, svanharmelen commented on freeze_periods.go
> +// UpdateFreezePeriodOptions represents the available UpdateFreezePeriodOptions() options.
```suggestion
// UpdateFreezePeriodOptions represents the available UpdateFreezePeriodOptions()
// options.
```

2020-09-23 07:58 UTC, pcnc commented
Thanks for the suggestions! All requested changes were implemented.

2020-09-23 09:03 UTC, svanharmelen approved these changes
Super nice, thanks @pcnc!

2020-09-23 09:03 UTC, merged