User memberships
xanzy/go-gitlab pull request #953
Opened 2020-10-05 20:28 UTC by cpackingham

2020-10-08 07:03 UTC, svanharmelen requested changes
Thanks @cpackingham! Few super minor comments, looks good otherwise 👍🏻

2020-10-08 07:03 UTC, svanharmelen commented on testdata/get_user_memberships.json
> +]
Please make sure the file ends with a newline.

2020-10-08 07:03 UTC, svanharmelen commented on users_test.go
> +
```suggestion
```

2020-10-08 07:03 UTC, svanharmelen commented on users_test.go
> +	require.Equal(t, want, memberships)
While require is fine, assert would probably also be a good option here.

2020-10-08 21:18 UTC, cpackingham commented
Okay I think I got all of the suggestions in, how does it look?

2020-10-09 06:16 UTC, svanharmelen approved these changes
Thanks @cpackingham! LGTM!

2020-10-09 06:16 UTC, merged