Add Milestones and ReleasedAt
xanzy/go-gitlab pull request #992
Opened 2020-12-01 15:35 UTC by WinterYukky

Resolves #991

- [x] add Milestones and ReleasedAt to CreateReleaseOptions
- [x] add Milestones and ReleasedAt to UpdateReleaseOptions
- [x] add unit test.

2020-12-01 19:52 UTC, svanharmelen requested changes
Looks good, but needs a small tweak...

2020-12-01 19:52 UTC, svanharmelen commented on releases.go
> +	Milestones  *[]string      `url:"milestones,omitempty" json:"milestones,omitempty"`
This should not be a pointer as the zero value of a slice is already `nil`

2020-12-01 19:52 UTC, svanharmelen commented on releases.go
> +	Milestones  *[]string  `url:"milestones,omitempty" json:"milestones,omitempty"`
Same here about the pointer...

2020-12-02 03:54 UTC, WinterYukky commented
@svanharmelen Thank you for quickly review😊
I fixed it.  Please check.

2020-12-02 07:54 UTC, svanharmelen approved these changes

2020-12-02 07:54 UTC, svanharmelen commented
Thanks @WinterYukky! LGTM!

2020-12-02 07:54 UTC, merged